### ISSUE TITLE
Needs tests.

### ISSUE THREAD

**Issue by latentflip** [AmpersandJS/ampersand-form-view#1]

**Comment by chesles** [comment]
Was writing some tests against something that uses this, and ran into some issues, particularly PhantomJS 1.9.x's lack of support for `Function.prototype.bind`. Started writing some tests here following the testing patterns used in other ampersand modules: https://github.com/chesles/ampersand-form-view/compare/tests

**Comment by imorrison** [comment]
Whenever I use PhantomJS I always add a bind polyfill. Here is one that I often use: https://www.npmjs.com/package/bindpolyfill

**Comment by chesles** [comment]
@imorrison yep, that's the exact polyfill I pulled in to make it work :)

**Comment by HenrikJoreteg** [comment]
apparently this never got closed even though it was done... closing.
