### ISSUE TITLE
Extend from ampersand-view or rename

### ISSUE THREAD

**Issue by mikehedman** [AmpersandJS/ampersand-form-view#20]
This module uses the same naming as other Ampersand views, but it does not extend ampersand-view, nor does it follow the view conventions specified in http://ampersandjs.com/docs#ampersand-view.
I would suggest re-coding so that it extends from ampersand-view, or renaming this module to just ampersand-form to avoid confusion.
A similar issue has been raised against ampersand-select-view: https://github.com/AmpersandJS/ampersand-select-view/issues/2

**Comment by mmacaula** [comment]
+1 on this, i just got bitten by trying to use a mixin with `extend` and suddenly my view disappears.  :(

**Comment by bbbales2** [comment]
Yes agreed. I was trying to use some of the ampersand-view helper functions (renderSubview) when I found it wasn't sub-classed.

Also I think I had some problems with not being able to pass a template into the constructor and get the form to use that instead of the default '<form></form>' element.

**Comment by cdaringe** [comment]
See #42

**Comment by shaharmor** [comment]
+1

**Comment by pgilad** [comment]
Closed via https://github.com/AmpersandJS/ampersand-form-view/commit/06939cdc52a9e9193314cadc56d780aacee8ef6a
