### ISSUE TITLE
Render happens before Initialize

### ISSUE THREAD

**Issue by bbbales2** [AmpersandJS/ampersand-form-view#21]
Try this:

```javascript
var AmpersandFormView = require('ampersand-form-view');

var TestForm = AmpersandFormView.extend({
    initialize: function(attr, options) {
        console.log('1');
    },
    render: function()
    {
        console.log('2');
    }
});

new TestForm();
```

The output is:

```
2
1
```

This doesn't seem right to me. Ampersand-view does it the other way.

I think the issue is lines 31-35 in the src. Three things happen:
1. Render the form
2. Render all the fields
3. Initialize

I had to reorder them as 3, 2, 1 because:
* I needed information passed from the constructor to build my field elements dynamically. I could not just declare the fields variable in the .extend call as shown in the examples.

* The fields needed to be rendered by the time I get to my render call because I append another element (a submit button) and apply some style-hacks (set autocomplete to off for all fields in the form via jquery properties) that need this.el to be populated.

My render looks something like:
```javascript
render: function()    {
    AmpersandFormView.prototype.render.apply(this, arguments); // Get all the default FormView stuff done and create Fields

    $( this.el ).find('input').prop('autocomplete', 'off'); // Turn off autocomplete

    this.button = $('<input type="submit">').appendTo( $( this.el ) ); // Add a submit button!
}
```
--

I also ended up just making step 2 part of the FormView render call. I don't see why the fields would try to render if the FormView itself hasn't tried to render.

Does this make sense?

Thanks,
Ben

**Comment by bbbales2** [comment]
I have a patch for this in my fork:

https://github.com/bbbales2/ampersand-form-view/commit/510b9b3e3d3d251da44f3de1aebd29cfb7be7f06

**Comment by bbbales2** [comment]
Ehh, the previous commit wasn't quite enough. I worry maybe I'm just hacking stuff up so it works for my own code, but I'll just leave this here https://github.com/bbbales2/ampersand-form-view/commit/97d3b7ca8b30adbe70de5f4a5d5c6eaa43956555

**Comment by cdaringe** [comment]
I didn't realize this was an open issue.  This is actually resolved in recent versions of form-view :smile:
