### ISSUE TITLE
New object on every `render()`?

### ISSUE THREAD

**Issue by Zearin** [AmpersandJS/ampersand-form-view#24]
I’m a little confused about the example in the `README.md`.  

Inside the class’s `render()`, the code calls `new FormView` and `this.registerSubview`.  To me, these seem like things that should be in `initialize()` instead.  

Is there a reason that they are in `render()`?  Will rendering break if that code is moved?

**Comment by Zearin** [comment]
Also, what about using a `subviews:  {…}` hash inside of `extend()`?  Will it work with `FormView`?

**Comment by cdaringe** [comment]
hey @Zearin, im looking [at render( ) now](https://github.com/AmpersandJS/ampersand-form-view/blob/master/ampersand-form-view.js#L143), and not observing this behavior.  perhaps this was old timey functionality!  I think we will eventually want to migrate to &-view, but nothing has been settled ATM!
