### ISSUE TITLE
No `FormView.extend()`?

### ISSUE THREAD

**Issue by Zearin** [AmpersandJS/ampersand-form-view#25]
In the README.md example, the class simply extends the Ampersand’s normal `View`, and then recreates a `new FormView` on every `render()`.  (I asked about the implications of this in Issue #24.)

Why not just extend `FormView`?  Does it not work?  Are there disadvantages?  

I have been (intensely) learning Ampersand for the past several weeks, but I am a little confused about all this.  The example is doing many things differently from what I have come to expect when using `extend` to create custom States/Models/Views.

**Comment by cdaringe** [comment]
`extend` was added after this question, but didn't have the full `State` capability that may have expected expected.  see semi-duplicate #25, and PR #42.  Thanks!
