### ISSUE TITLE
aggregate functions

### ISSUE THREAD

**Issue by wraithgar** [AmpersandJS/ampersand-form-view#28]
If all the fields have a getValue and setValue then it would be possible to expose them at this module as `getValue(field)` and `setValue(field, value)`

A `getValues` and `setValues` that returned and accepted a hash would also be possible.

**Comment by cdaringe** [comment]
@wraithgar, yes, absolutely.  perhaps a simple module to publish would be ampersand-field-view-conventions, much like the normal view convention lib.  each field view's test suite runs it, and we are on our way.  someone asked in the gitter recently if they could 'save' their form, which ultimately means reconstruct it.  with `setValue` and `getValue` in each FieldView, form caching & reconstruction becomes feasible within the ampersand toolchain.

actually, it looks like latentflip [already had this idea](https://github.com/AmpersandJS/ampersand-view-conventions/blob/master/ampersand-view-conventions.js#L48).  we just need to beef it up and add the test suite to each FieldView.

**Comment by cdaringe** [comment]
##### review formField view conventions
 latentflip has some good fieldView requirements in there already. here are some additions I think should be considered:
- [ ] shall have a default message container hook? `data-hook="{name}-message-container"`
- [ ] shall have a default message text hook? `data-hook="{name}-message-text"`
- [ ] text hook el shall be direct child of container hook el
- [ ] should support `autoRender: false` option (possibly redundant if we want to move FieldViews to extend ampersand-view)
- [ ] should have a `.value !== undefined` before render, if `autoRender: false`
- [ ] should have an explicit boolean `.valid` after construction, regardless of rendered state

##### To be updated (official) with FieldView conventions
- [ ] ampersand-select-view
- [ ] ampersand-input-view
- [ ] ampersand-checkbox-view
- [ ] ampersand-array-input-view

##### To recommend for update (community) with FieldView conventions
- [ ] ampersand-expanding-textarea-view
- [ ] ampersand-floatinglabel-input-view
- [ ] ampersand-filereader-input-view ?

**Comment by wraithgar** [comment]
I'm not sure I understand the text hook el one.

**Comment by cdaringe** [comment]
text updated

**Comment by wraithgar** [comment]
Great, thanks for doing all that legwork!  Looks good to me.  My gut says those default container hooks are a little too locked-in but it appears that's already the de facto standard so here we are.  Can you make issues in those 4 core modules pointing to this at least? Checkboxes are hard to manage in issues (see my failure to properly manage https://github.com/AmpersandJS/ampersand/issues/95)

**Comment by cdaringe** [comment]
hey gar, ya, I will.  adding capability extend `beforeSubmit`.  I have no hard qualms with removing the container hooks, although it might be nice!

**Comment by cdaringe** [comment]
issues filed

**Comment by gdibble** [comment]
i see that: *ampersand-filereader-input-view ?*
i will watch this thread for view-convention updates and then update the module accordingly

**Comment by cdaringe** [comment]
after reviewing the formField view convention requirements code, it's clear that the criteria was well thought through on first pass.  we really don't need to add more, beyond that in open pull requests.  

simply adding the test requirements to each field view should suffice, then the aggregate functions should be able to be added safely

**Comment by gdibble** [comment]
*obvious question or not:* &nbsp; &nbsp; is there a posted **`SPEC`** for form-field-view developers to follow?

**Comment by cdaringe** [comment]
Yessir!  https://ampersandjs.com/learn/forms#form-input-view-conventions .
What is not there is making sure to add the &-view convention test suite to
your field view tests
https://github.com/AmpersandJS/ampersand-view-conventions.  See
ampersand-select-view for an example of how the tape suite is set up
concisely to execute the view convention tests before it runs its own.

On Sunday, April 5, 2015, Gabriel Dibble <notifications@github.com> wrote:

> *obvious question or not:*     is there a posted *SPEC* for
> form-field-view developers to follow?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AmpersandJS/ampersand-form-view/issues/28#issuecomment-89932251>
> .
>


-- 
Chris Dieringer
p: (503)358-8577
e: cdieringer@mrn.org
w: http://cdaringe.net/
