### ISSUE TITLE
Complete or submitted property

### ISSUE THREAD

**Issue by cdaringe** [AmpersandJS/ampersand-form-view#36]
@wraithgar, I can extend my own formView to accommodate my needs, but thought this feature may be useful for others as well.  How would you feel about a PR for adding a `complete` property to the FormView?

It would signify that the form is in a state where all fields have been validated and the form has been submitted (at least once).  The case could exist where you leave your form on the page post-submit, and then additional changes are made.  This state could *feasibly invalidate* the intent of `complete` in that the form would be `complete`, but still clearly inwork as it exposed to the user.  However, this could simply be documented as an edge case.

What's driving this idea is that I'm making a form-manager/questionnaire view.  I need to get state updates on many forms from a single source.  Another idea is to perhaps add a mixin to support this feature.

`complete`, `submitted`, `beenSubmitted`, `submitCount`, `completeCount` -- all could imply the same thing

**Comment by wraithgar** [comment]
So changing a field in a form would set complete back to false?

**Comment by cdaringe** [comment]
id think if the form is invalid *and* submitted again, then complete would toggle back to false

**Comment by wraithgar** [comment]
I think the property should be `submitted` and a quick logic tree explaining its state is in order. If you've already got code you're using a PR may be easier to start the discussion.

**Comment by cdaringe** [comment]
Cool.  We'll, let's close this discussion for now, and perhaps I'll shoot something your way in the coming weeks, or even a working demo
