### ISSUE TITLE
form-view and field-view rendered relation inconsistency

### ISSUE THREAD

**Issue by cdaringe** [AmpersandJS/ampersand-form-view#41]
### problem statement
Some formField views render() immediately on construction.  This is undesired behavior.
If the FormView doesn't render immediately, some child fieldViews will still claim `.rendered`,
which is a false claim.  Consequently those child-views may not display at `form.render()` as a FormView will think that they are *already* rendered. :(

### potential solutions
1. update each FieldFiew to *not* autorender.  e.g. match &-view behavior
    1. a complimentary update to view-conventions would likely need to be required
        1. maybe a test for visibility or if a parentNode is set, which it shouldn't be, unless render has been called directly or if autoRender enabled
1. update fieldViews to extend &-view, and support `autoRender` in `initialize()`
    1. this is a nice solution, as the fieldViews become extendable for user needs with all of the other goodies &-view offers

this was likely introduced by my update to support `autoRender` in &-form-view, but regardless, needs to be addressed.

**Comment by wraithgar** [comment]
Is this at all related to https://github.com/AmpersandJS/ampersand-view/issues/112?

**Comment by cdaringe** [comment]
no, it is not.  however, rendered events don't happen on non- &-view form field views

**Comment by cdaringe** [comment]
@wraithgar, pretty much what I'm getting is that is that I'm going to go through all of the fields, remove `render()` out of `initialize()`, and likely extend from ampersand-view.  I hope this will be well received?

**Comment by mrDarcyMurphy** [comment]
I'm running into this as well. My form initializes, adds the fields, but doesn't render them because the form itself hasn't been rendered. 

I've tried swapping the order of lines [31](https://github.com/AmpersandJS/ampersand-form-view/blob/master/ampersand-form-view.js#L31) & [33](https://github.com/AmpersandJS/ampersand-form-view/blob/master/ampersand-form-view.js#L33), but that didn't work because while the fields get rendered they aren't actually applied to the real DOM.

I haven't tried it yet, but the solution might be to follow the same pattern ampersand-view uses for its subviews. [`_initializeSubviews`](https://github.com/AmpersandJS/ampersand-view/blob/master/ampersand-view.js#L255) is called before `render`, then [`_parseSubview`](https://github.com/AmpersandJS/ampersand-view/blob/master/ampersand-view.js#L265) prepares the views but doesn't render them until a change is registered.

**Comment by cdaringe** [comment]
@mrDarcyMurphy, because of [line 159](https://github.com/AmpersandJS/ampersand-form-view/blob/master/ampersand-form-view.js#L159) and because the fieldViews are `rendered`, form view will skip 'em, regardless of *when* formView is rendered.  the trick is to let form view handle the rendering of the field views, or manually render the field views (vs. the fields rendering themselves!).  I have updates in a series of field view repos to patch this.  which controls are you wrestling with?

**Comment by cdaringe** [comment]
for now, you should be able to downgrade form view to 2.x and use controls that self render.  if you're not sure if they self render, perhaps just pass `autoRender: true` to them all as safety!

**Comment by achingbrain** [comment]
I just ran into this problem too after updating ampersand-form-view to the latest version, specifically the check for [`fieldView.rendered`](https://github.com/AmpersandJS/ampersand-form-view/blob/master/ampersand-form-view.js#L159) is preventing select and checkbox views from being added to the form in form-view v3 as they [render](https://github.com/AmpersandJS/ampersand-select-view/blob/master/ampersand-select-view.js#L51) [themselves](https://github.com/AmpersandJS/ampersand-checkbox-view/blob/master/ampersand-checkbox-view.js#L34) during their constructors.

**Comment by mrDarcyMurphy** [comment]
I tried the autoRender but it didn't make a difference in my case. What I found instead was that I was setting a bound property during the initialize method which, as far as I could tell, was causing DOM changes to happen before things had rendered. 

My solution was to do this instead: 
``` javascript
initialize: function () {

  this.once("change:rendered", this.setVisibility, this);
}
```

**Comment by mrDarcyMurphy** [comment]
Also… I had upgraded from 2.x to escape a different bug where things were rendering twice. Might have been due to the same cause.

**Comment by cdaringe** [comment]
migrating all &-view deps to 8.x should resolve this
