### ISSUE TITLE
Form in a view (should be very simple =)

### ISSUE THREAD

**Issue by gnimmelf** [AmpersandJS/ampersand-form-view#49]
Oki, I'm new to Ampersand, but here goes;

I have this form:
```
var FormView = require('ampersand-form-view');
var InputView = require('ampersand-input-view');

EditForm = FormView.extend({
  initialize: function(options) {
    debug('initialize', this.el, this.autoRender, this.submitCallback)
  },

  fields: function () {
    debug('fields!')

    var fields = [
      new InputView({
        label: 'Name',
        name: 'name',
        value: utils.getDotted(this, 'model.name'),
        placeholder: 'Name',
        parent: this
      })
    ];

    debug('fields', fields)

    return fields;
  }
});
```

And I want to use it in a couple of views, the `render`-method exemplified here:
```
render: function () {
    this.renderWithTemplate();

    this.form = new EditForm({
      autoRender: true,
      el: this.query('.edit-form'),

      submitCallback: function (data) {
        debug('submit', data);
      }
    });

    this.registerSubview(this.form);
    return this
  }
```
-this does not work.

Embedding the form code in a non-extended `ampersand-form` does work:
```
render: function () {
    this.renderWithTemplate();

    this.form = new FormView({
      autoRender: true,
      el: this.query('.edit-form'),
      fields: [
        new InputView({
          label: 'Name',
          name: 'name',
          value: utils.getDotted(this, 'model.name'),
          placeholder: 'Name',
          parent: this
        })
      ],
      submitCallback: function (data) {
        debug('submit', data);
      }
    });

    this.registerSubview(this.form);
    return this
  }
```

What am I missing?

**Comment by cdaringe** [comment]
hey @gnimmelf!

looks like you are mixing up what goes in `.extend` and what goes inside the constructor, e.g. new EditForm({ur-options-here}).  take a closer peek at the API docs, and you'll find that your method overriding goes in .extend, but other options, like fields, go into the constructor!

as a forewarning, many "features" of FormView actually extend from "View" itself.  If you need to override `initialize` and are willing to call `View.prototype.call(this)` safely, I recommend doing so until you are more comfortable with the lib.  You don't need to, but it will likely be helpful as you're just fist learnin' it.  It will make sure you get all the other &-View goodies.

write back with more Qs as necessary.  feel free to post a requirebin fiddle too if youd like
