### ISSUE TITLE
Update ampersand-view dependency

### ISSUE THREAD

**Issue by achingbrain** [AmpersandJS/ampersand-form-view#60]
Versions of ampersand-view before 9.0.2 depend on get-object-path@0.0.2 - this has just been [removed from npm](https://github.com/azer/get-object-path/issues/1).

Any chance of this module updating it's ampersand-view dep?

**Comment by wraithgar** [comment]
Yes a PR to update that would most likely be quickly accepted.

**Comment by achingbrain** [comment]
Do you know what the breaking changes are between 8 and 9?

**Comment by wraithgar** [comment]
Copying reply from https://github.com/AmpersandJS/ampersand-select-view/issues/71


> Yep! There were two small breaking changes in some defaults, outlined here: https://github.com/AmpersandJS/ampersand-view#changelog

> I don't think those specifically affect this module, but because this is returning an ampersand-view a PR bumping 8 to 9 would constitute a major bump in this module.
