### ISSUE TITLE
listenTo not a method?

### ISSUE THREAD

**Issue by dhritzkiv** [AmpersandJS/ampersand-form-view#8]
I just noticed that `listenTo`, `listenToOnce`, and `listenToAndRun` are not methods of the form-view instance. Is this correct? Shouldn't it inherit it those from `ampersand-view`?

**Comment by cdaringe** [comment]
hey @dhritzkiv! at the time of writing, they are still unavailable.  please see PR #42.  would love to get your review on it too, as i know you're a power-user

**Comment by pgilad** [comment]
Closed via https://github.com/AmpersandJS/ampersand-form-view/commit/06939cdc52a9e9193314cadc56d780aacee8ef6a
